version: '3.8'

services:
  backend:
    image: sergioalcala/ec-2-backend:latest
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    networks:
      - app-network

  frontend:
    image: sergioalcala/ec-2-frontend:latest
    ports:
      - "3001:4000"
    environment:
      NODE_ENV: production
    command: npm run dev -- --port 4000 --host
    networks:
      - app-network

networks:
  app-network:
    driver: bridge