name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Backend Docker Image
        run: sudo docker pull sergioalcala/ec-2-backend:latest
      - name: Delete old Backend Docker Image
        run: sudo docker rm -f sergioalcala/ec-2-backend || true
      - name: Pull Frontend Docker Image
        run: sudo docker pull sergioalcala/ec-2-frontend:latest
      - name: Delete old Frontend Docker Image
        run: sudo docker rm -f sergioalcala/ec-2-frontend || true
      - name: Run docker-compose
        run: sudo docker-compose -f docker-compose.yml up -d
