name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Backend Docker Image
        run: sudo docker pull sergioalcala/ec-2-backend:latest
      - name: Delete old Backend Docker Image
        run: sudo docker rmi -f sergioalcala/ec-2-backend:latest || true
      - name: Pull Frontend Docker Image
        run: sudo docker pull sergioalcala/ec-2-frontend:latest
      - name: Delete old Frontend Docker Image
        run: sudo docker rmi -f sergioalcala/ec-2-frontend:latest || true
      - name: Run Backend Docker Image
        run: sudo docker run -d -p 3000:3000 --name ec-2-backend sergioalcala/ec-2-backend:latest
      - name: Run Frontend Docker Image
        run: sudo docker run -d -p 3001:4000 --name ec-2-frontend sergioalcala/ec-2-frontend:latest
