name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run docker-compose
        working-directory: ${{ github.workspace }}
        run: docker-compose up -d --build
