name: CI

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Login Docker
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build backend the Docker image
        run: docker build --platform linux/amd64 -t sergioalcala/ec-2-backend:latest -f ./backend/Dockerfile ./backend
      - name: Push backend to dockerhub
        run: docker push sergioalcala/ec-2-backend:latest

      - name: Build frontend the Docker image
        run: docker buildx build --platform linux/amd64 --build-arg API_URL=${{ secrets.API_URL }} --build-arg CLIENT_ID=${{ secrets.CLIENT_ID }} --build-arg AUTHORITY=${{ secrets.AUTHORITY }} -t sergioalcala/ec-2-frontend:latest -f ./frontend/Dockerfile ./frontend

      - name: Push frontend to dockerhub
        run: docker push sergioalcala/ec-2-frontend:latest
